### ISSUE TITLE
tests: Setting pipe capacity can sometimes fail

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#4475]
Based on the recent CI failure:
```
[2022-08-10T11:09:41.414Z] failures:
[2022-08-10T11:09:41.414Z] 
[2022-08-10T11:09:41.414Z] ---- parallel::test_vhost_user_net_tap_multiple_queues stdout ----
[2022-08-10T11:09:41.414Z] 
[2022-08-10T11:09:41.414Z] 
[2022-08-10T11:09:41.414Z] ==== Start cloud-hypervisor command-line ====
[2022-08-10T11:09:41.414Z] 
[2022-08-10T11:09:41.414Z] "target/aarch64-unknown-linux-musl/release/cloud-hypervisor" "--cpus" "boot=2" "--memory" "size=512M,hotplug_size=2048M,shared=on" "--kernel" "/root/workloads/Image" "--cmdline" "root=/dev/vda1 console=hvc0 rw systemd.journald.forward_to_console=1" "--disk" "path=/tmp/chAgpPkl/osdisk.img" "path=/tmp/chAgpPkl/cloudinit" "--net" "vhost_user=true,mac=12:34:56:78:90:38,socket=/tmp/chAgpPkl/vunet.sock,num_queues=4,queue_size=1024,vhost_mode=client" "--api-socket" "/tmp/chAgpPkl/cloud-hypervisor.sock" "-v"
[2022-08-10T11:09:41.414Z] 
[2022-08-10T11:09:41.414Z] ==== End cloud-hypervisor command-line ====
[2022-08-10T11:09:41.414Z] 
[2022-08-10T11:09:41.414Z] 
[2022-08-10T11:09:41.414Z] thread 'parallel::test_vhost_user_net_tap_multiple_queues' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "resizing pipe w/ 'fnctl' failed!" }', tests/integration.rs:830:36
[2022-08-10T11:09:41.414Z] stack backtrace:
[2022-08-10T11:09:41.414Z]    0: rust_begin_unwind
[2022-08-10T11:09:41.414Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
[2022-08-10T11:09:41.414Z]    1: core::panicking::panic_fmt
[2022-08-10T11:09:41.414Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
[2022-08-10T11:09:41.414Z]    2: core::result::unwrap_failed
[2022-08-10T11:09:41.414Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
[2022-08-10T11:09:41.414Z]    3: core::result::Result<T,E>::unwrap
[2022-08-10T11:09:41.414Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1078:23
[2022-08-10T11:09:41.414Z]    4: integration::test_vhost_user_net
[2022-08-10T11:09:41.414Z]              at ./tests/integration.rs:830:17
[2022-08-10T11:09:41.414Z]    5: integration::parallel::test_vhost_user_net_tap_multiple_queues
[2022-08-10T11:09:41.414Z]              at ./tests/integration.rs:2981:9
[2022-08-10T11:09:41.414Z]    6: integration::parallel::test_vhost_user_net_tap_multiple_queues::{{closure}}
[2022-08-10T11:09:41.414Z]              at ./tests/integration.rs:2980:5
[2022-08-10T11:09:41.414Z]    7: core::ops::function::FnOnce::call_once
[2022-08-10T11:09:41.414Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
[2022-08-10T11:09:41.414Z]    8: core::ops::function::FnOnce::call_once
[2022-08-10T11:09:41.414Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
[2022-08-10T11:09:41.414Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

We can see the test `test_vhost_user_net_tap_multiple_queues` failed when trying to update the pipe capacity of both `stdout` and `stderr` with the following error:
```
Err` value: Custom { kind: Other, error: "resizing pipe w/ 'fnctl' failed!" }', tests/integration.rs:830:36
```

This is probably due to the limit found at `/proc/sys/fs/pipe-user-pages-soft` being reached, and the `fcntl()` system call returning `EPERM`.

We should enable more precise error handling in the tests to identify and confirm the reason why `fcntl()` can sometimes fail.
If it confirms that we get `EPERM`, we should simply update the `/proc/sys/fs/pipe-user-pages-soft` to `0`, which means there's no limit applied.

**Comment by sboeuf** [comment]
Well we haven't seen any failure related to pipe capacity, so I guess we can close it. I had added some extra logs which will help us spot the problem if it ever happens.
