### ISSUE TITLE
ci: test_windows_guest_disk_hotplug is flaky on aarch64

### ISSUE THREAD

**Issue by sboeuf** [cloud-hypervisor/cloud-hypervisor#4583]
We've recently observed the same error being reported on aarch64 (1470, 1474, 1477) and x86_64 builds (1481) for the test `test_windows_guest_disk_hotplug`.

Here is the log:
```
[2022-09-01T04:01:27.554Z] failures:
[2022-09-01T04:01:27.554Z] 
[2022-09-01T04:01:27.554Z] ---- windows::test_windows_guest_disk_hotplug stdout ----
[2022-09-01T04:01:27.554Z] 
[2022-09-01T04:01:27.554Z] 
[2022-09-01T04:01:27.554Z] ==== Start cloud-hypervisor command-line ====
[2022-09-01T04:01:27.554Z] 
[2022-09-01T04:01:27.554Z] "target/aarch64-unknown-linux-musl/release/cloud-hypervisor" "--api-socket" "/tmp/chGGIcoI/cloud-hypervisor.sock" "--cpus" "boot=2,kvm_hyperv=on" "--memory" "size=4G" "--kernel" "/root/workloads/CLOUDHV_EFI.fd" "--serial" "tty" "--console" "off" "--disk" "path=/dev/mapper/windows-snapshot-chLejDBc" "--net" "tap=,mac=12:34:56:78:90:02,ip=192.168.2.1,mask=255.255.255.0" "-v"
[2022-09-01T04:01:27.554Z] 
[2022-09-01T04:01:27.554Z] ==== End cloud-hypervisor command-line ====
[2022-09-01T04:01:27.554Z] 
[2022-09-01T04:01:27.554Z] 
[2022-09-01T04:01:27.554Z] [70, 111, 114, 109, 97, 116, 116, 105, 110, 103, 32, 39, 47, 116, 109, 112, 47, 116, 101, 115, 116, 45, 104, 111, 116, 112, 108, 117, 103, 45, 49, 46, 114, 97, 119, 39, 44, 32, 102, 109, 116, 61, 114, 97, 119, 32, 115, 105, 122, 101, 61, 49, 48, 52, 56, 53, 55, 54, 48, 48, 10]
[2022-09-01T04:01:27.555Z] [47, 100, 101, 118, 47, 108, 111, 111, 112, 52, 10]
[2022-09-01T04:01:27.555Z] []
[2022-09-01T04:01:27.555Z] []
[2022-09-01T04:01:27.555Z] [47, 100, 101, 118, 47, 108, 111, 111, 112, 52, 10]
[2022-09-01T04:01:27.555Z] [109, 107, 102, 115, 46, 102, 97, 116, 32, 52, 46, 49, 32, 40, 50, 48, 49, 55, 45, 48, 49, 45, 50, 52, 41, 10]
[2022-09-01T04:01:27.555Z] []
[2022-09-01T04:01:27.555Z] thread 'windows::test_windows_guest_disk_hotplug' panicked at 'assertion failed: `(left == right)`
[2022-09-01T04:01:27.555Z]   left: `2`,
[2022-09-01T04:01:27.555Z]  right: `1`', tests/integration.rs:7577:13
[2022-09-01T04:01:27.555Z] stack backtrace:
[2022-09-01T04:01:27.555Z]    0: rust_begin_unwind
[2022-09-01T04:01:27.555Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
[2022-09-01T04:01:27.555Z]    1: core::panicking::panic_fmt
[2022-09-01T04:01:27.555Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
[2022-09-01T04:01:27.555Z]    2: core::panicking::assert_failed_inner
[2022-09-01T04:01:27.555Z]    3: core::panicking::assert_failed
[2022-09-01T04:01:27.555Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:181:5
[2022-09-01T04:01:27.555Z]    4: integration::windows::test_windows_guest_disk_hotplug::{{closure}}
[2022-09-01T04:01:27.555Z]              at ./tests/integration.rs:7577:13
[2022-09-01T04:01:27.555Z]    5: std::panicking::try::do_call
[2022-09-01T04:01:27.555Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
[2022-09-01T04:01:27.555Z]    6: __rust_try
[2022-09-01T04:01:27.555Z]    7: std::panicking::try
[2022-09-01T04:01:27.555Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
[2022-09-01T04:01:27.555Z]    8: std::panic::catch_unwind
[2022-09-01T04:01:27.555Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
[2022-09-01T04:01:27.555Z]    9: integration::windows::test_windows_guest_disk_hotplug
[2022-09-01T04:01:27.555Z]              at ./tests/integration.rs:7541:17
[2022-09-01T04:01:27.555Z]   10: integration::windows::test_windows_guest_disk_hotplug::{{closure}}
[2022-09-01T04:01:27.555Z]              at ./tests/integration.rs:7514:5
[2022-09-01T04:01:27.555Z]   11: core::ops::function::FnOnce::call_once
[2022-09-01T04:01:27.555Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
[2022-09-01T04:01:27.555Z]   12: core::ops::function::FnOnce::call_once
[2022-09-01T04:01:27.555Z]              at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:248:5
[2022-09-01T04:01:27.555Z] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-09-01T04:01:27.555Z] ==== child killed by signal: 9 ====
```

Given this is sporadically failing, it's very likely the problem comes from the sleep time not being large enough before checking the device has been removed.

**Comment by sboeuf** [comment]
@weltling could you please have a look at this issue as it's failing quite often on aarch64.

**Comment by weltling** [comment]
@sboeuf thanks for tagging me on this and for preliminary taking care of the sporadic issue. At the time I went for enabling more tests for `aarch64`, I observed an instability with the other one `test_windows_guest_disk_hotplug_multi`, too. My assumption was as well some small timeout, but seems it might be something else, too. I'll dig into this, but it might be not quick, unfortunately, so keeping both disabled for now is just fine.

Thanks!

**Comment by sboeuf** [comment]
> @sboeuf thanks for tagging me on this and for preliminary taking care of the sporadic issue. At the time I went for enabling more tests for `aarch64`, I observed an instability with the other one `test_windows_guest_disk_hotplug_multi`, too. My assumption was as well some small timeout, but seems it might be something else, too. I'll dig into this, but it might be not quick, unfortunately, so keeping both disabled for now is just fine.
> 
> Thanks!

Sounds good, just keep us posted when you make some progress.

**Comment by weltling** [comment]
I've run the steps in the test manually and there doesn't seem to be an issue with the disk hotplug functionality. What I realize however, that in the `aarch64` Windows guest any powershell code is tremendously slow. In short term, it might be worth a try to rewrite the tests to not use PS.

For a longer term, digging into what exactly makes powershell that unstable would be needed. I still have an `aarch64` dev board, but the focus has shifted back to x86_64 at the moment. I'd suggest to try moving away from powershell first and see if it brings an improvement, the powershell issues investigation would be something to defer.

Thanks
