### ISSUE TITLE
Self-test does not pass after modifying io_uring to be disabled by default

### ISSUE THREAD

**Issue by ljrcore** [cloud-hypervisor/cloud-hypervisor#4897]
cloud-hypervisor v27.0.0

I changed io_uring to be disabled by default.
```
diff --git a/vmm/src/config.rs b/vmm/src/config.rs
index 95f113da..9c298079 100644
--- a/vmm/src/config.rs
+++ b/vmm/src/config.rs
@@ -1042,7 +1042,7 @@ impl Default for DiskConfig {
             vhost_user: false,
             vhost_socket: None,
             id: None,
-            disable_io_uring: false,
+            disable_io_uring: true,
             rate_limiter_config: None,
             pci_segment: 0,
         }
@@ -1114,7 +1114,7 @@ impl DiskConfig {
         let disable_io_uring = parser
             .convert::<Toggle>("_disable_io_uring")
             .map_err(Error::ParseDisk)?
-            .unwrap_or(Toggle(false))
+            .unwrap_or(Toggle(true))
             .0;
         let pci_segment = parser
             .convert("pci_segment")
```
Execute the self-test.
```
./scripts/run_unit_tests.sh
```
The test does not pass.
```
...
running 15 tests
test unit_tests::test_valid_vm_config_kernel ... ok
test unit_tests::test_valid_vm_config_default ... ok
test unit_tests::test_valid_vm_config_cmdline ... ok
test unit_tests::test_valid_vm_config_rng ... ok
test unit_tests::test_valid_vm_config_vdpa ... ok
test unit_tests::test_valid_vm_config_cpus ... ok
test unit_tests::test_valid_vm_config_serial_pty_console_pty ... ok
test unit_tests::test_valid_vm_config_serial_console ... ok
test unit_tests::test_valid_vm_config_pmem ... ok
test unit_tests::test_valid_vm_config_fs ... ok
test unit_tests::test_valid_vm_config_devices ... ok
test unit_tests::test_valid_vm_config_vsock ... ok
test unit_tests::test_valid_vm_config_memory ... ok
test unit_tests::test_valid_vm_config_net ... ok
test unit_tests::test_valid_vm_config_disks ... FAILED

failures:

---- unit_tests::test_valid_vm_config_disks stdout ----
thread 'unit_tests::test_valid_vm_config_disks' panicked at 'assertion failed: `(left == right)`
  left: `VmConfig { cpus: CpusConfig { boot_vcpus: 1, max_vcpus: 1, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None, features: CpuFeatures { amx: false } }, memory: MemoryConfig { size: 536870912, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: None, initramfs: None, cmdline: CmdlineConfig { args: "" }, payload: Some(PayloadConfig { firmware: None, kernel: Some("/path/to/kernel"), cmdline: None, initramfs: None }), disks: Some([DiskConfig { path: Some("/path/to/disk/1"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: None, disable_io_uring: true, pci_segment: 0 }, DiskConfig { path: Some("/path/to/disk/2"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: None, disable_io_uring: true, pci_segment: 0 }]), net: None, rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Null, iommu: false }, console: ConsoleConfig { file: None, mode: Tty, iommu: false }, devices: None, user_devices: None, vdpa: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false, platform: None }`,
 right: `VmConfig { cpus: CpusConfig { boot_vcpus: 1, max_vcpus: 1, topology: None, kvm_hyperv: false, max_phys_bits: 46, affinity: None, features: CpuFeatures { amx: false } }, memory: MemoryConfig { size: 536870912, mergeable: false, hotplug_method: Acpi, hotplug_size: None, hotplugged_size: None, shared: false, hugepages: false, hugepage_size: None, prefault: false, zones: None }, kernel: None, initramfs: None, cmdline: CmdlineConfig { args: "" }, payload: Some(PayloadConfig { firmware: None, kernel: Some("/path/to/kernel"), cmdline: None, initramfs: None }), disks: Some([DiskConfig { path: Some("/path/to/disk/1"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }, DiskConfig { path: Some("/path/to/disk/2"), readonly: false, direct: false, iommu: false, num_queues: 1, queue_size: 128, vhost_user: false, vhost_socket: None, rate_limiter_config: None, id: None, disable_io_uring: false, pci_segment: 0 }]), net: None, rng: RngConfig { src: "/dev/urandom", iommu: false }, balloon: None, fs: None, pmem: None, serial: ConsoleConfig { file: None, mode: Null, iommu: false }, console: ConsoleConfig { file: None, mode: Tty, iommu: false }, devices: None, user_devices: None, vdpa: None, vsock: None, iommu: false, sgx_epc: None, numa: None, watchdog: false, platform: None }`', src/main.rs:657:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:181:5
   4: cloud_hypervisor::unit_tests::compare_vm_config_cli_vs_json
             at ./src/main.rs:657:13
   5: cloud_hypervisor::unit_tests::test_valid_vm_config_disks::{{closure}}
             at ./src/main.rs:974:13
   6: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/slice/iter/macros.rs:211:21
   7: cloud_hypervisor::unit_tests::test_valid_vm_config_disks
             at ./src/main.rs:897:9
   8: cloud_hypervisor::unit_tests::test_valid_vm_config_disks::{{closure}}
             at ./src/main.rs:896:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    unit_tests::test_valid_vm_config_disks

test result: FAILED. 14 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass '-p cloud-hypervisor --bin cloud-hypervisor'
```
I have read the relevant commits and [issues](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/535), but I still don't understand the definition and origin of the CLI and HTTP API. 

How can I pass all unit tests with io_uring disabled by default?

Thanks

**Comment by rbradford** [comment]
I would expect it to fail. Those unit tests check the serialisation/deserialisation of the config. By changing the default on the parameter you're changing the serialisation output and thus what it matches against.

Please don't abuse an option that was only added for our internal purposes for our testing. It is not supported as part of the API.

**Comment by rbradford** [comment]
@ljrcore We don't support disabling the probing of `io_uring`. The functionality it provides is a huge improvement and you really should run a kernel that supports it. That control exists exclusively for the testing of the behaviour when it isn't present on the host. You shouldn't use it for controlling the io_uring feature.
